### PR TITLE
WMSID: 11254 - Updated steps and images due to the UI changes

### PR DESCRIPTION
**Pull request by yutakats**
# WMS ID 11254

Updated steps and images to go with the latest OCI UI, updated steps where service behaviors changed over time. Covered Login methods, Menu item contents, Features/widgets locations, UI look and feel, and minor feature changes. 

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramonamagadan18 — CHANGES_REQUESTED** [review]
Hi @yutakats! Please make sure that the user name, root, and compartment are not shown in the images.

**Comment by yutakats** [comment]
Hi Ramona,

I have updated the files across the workshop. Please review and let me know if further changes have to be made.

Thank you,

Yutaka

From: Ramona Magadan ***@***.***>
Date: Monday, June 10, 2024 at 12:03 AM
To: oracle-livelabs/oci ***@***.***>
Cc: Yutaka Takatsu ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] WMSID: 11254 - Updated steps and images due to the UI changes (PR #369)

@ramonamagadan18 requested changes on this pull request.

Hi @yutakats<https://urldefense.com/v3/__https:/github.com/yutakats__;!!ACWV5N9M2RV99hQ!Kzghp3Tp1rkEfg4CPyMWYb6qNUZzUnMtXZtP0pUQvWhTrdLPbbJqYDtlonq9jterGy6jqJT7rIUUcb54qRh3GBQAtJvZ$>! Please make sure that the user name, root, and compartment are not shown in the images.

**Review by ramonamagadan18 — CHANGES_REQUESTED** [review]
Hi @yutakats! There are still two images where the compartment name is visible:
once-apm-getstarted/06-save-search/images/6-4-5-move-query-to-top.png;
oci-apm-getstarted/06-save-search/images/6-5-3-click-te.png;
Please modify them.

**Comment by yutakats** [comment]
Hi Ramona,

Ah good catch.. I have updated the two files I missed and checked in just now. Please review.

Thank you,

Yutaka

From: Ramona Magadan ***@***.***>
Date: Monday, June 10, 2024 at 11:51 PM
To: oracle-livelabs/oci ***@***.***>
Cc: Yutaka Takatsu ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] WMSID: 11254 - Updated steps and images due to the UI changes (PR #369)

@ramonamagadan18 requested changes on this pull request.

Hi @yutakats<https://urldefense.com/v3/__https:/github.com/yutakats__;!!ACWV5N9M2RV99hQ!LQerlRA-ayt31-1wNOZvzaj-kqG6y5ndrw_uenJgT20xZ4m2S3JAIl_DDVBcYdfz65MmQ_2lcaAmkRLYaoufoXjS5q8X$>! There are still two images where the compartment name is visible:
once-apm-getstarted/06-save-search/images/6-4-5-move-query-to-top.png;
oci-apm-getstarted/06-save-search/images/6-5-3-click-te.png;
Please modify them.

**Review by ramonamagadan18 — APPROVED** [review]

**Comment by ramonamagadan18** [comment]
Hi @yutakats! Your branch has conflicts that must be resolved before it can be merged. Please solve the conflicts.

**Comment by yutakats** [comment]
Hi team, would anyone please advise how exactly I can resolve these conflicts?

***@***.***

Thank you,

Yutaka



From: Ramona Magadan ***@***.***>
Date: Tuesday, June 11, 2024 at 11:37 PM
To: oracle-livelabs/oci ***@***.***>
Cc: Yutaka Takatsu ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] WMSID: 11254 - Updated steps and images due to the UI changes (PR #369)

Hi @yutakats<https://urldefense.com/v3/__https:/github.com/yutakats__;!!ACWV5N9M2RV99hQ!L8oEoQReHQpVMFxl8LVOsvmKkWpo1Y5bjqfowJKiD40qE5_K50tsPUMtiQPeX8O5jVHuFAhPzDREoJ-UABldRFmAd1dm$>! Your branch has conflicts that must be resolved before it can be merged. Please solve the conflicts.

**Comment by ramonamagadan18** [comment]
Hi @yutakats! I sent you a Slack message with details.

**Review by ramonamagadan18 — APPROVED** [review]

**Pull request merged**
