### PR TITLE
WMS ID 11191 

### PR DESCRIPTION
**Pull request by yutakats**
# Add here your WMS ID
11191 - Automatically instrument Java microservices on Kubernetes using Oracle Application 
Quarterly Maintenance w/ major facelift to the workshop. Adopted a new method using OpenTelemetry to instrument application with OCI APM

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by yutakats** [comment]
Thank you, Carmen. Sorry my bad.

I went through the entire workshop and corrected the cases in the image files, grammatical errors in the mds, and changed the URL to the workshops to point to the livelabs.com workshops (instead of appexapps).

Thank you,

Yutaka



From: Carmen Berdant ***@***.***>
Date: Monday, December 2, 2024 at 5:46 AM
To: oracle-livelabs/oci ***@***.***>
Cc: Yutaka Takatsu ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] WMS ID 11191 (PR #435)

@carmenberdant1 requested changes on this pull request.

Hi @yutakats<https://urldefense.com/v3/__https:/github.com/yutakats__;!!ACWV5N9M2RV99hQ!KWD82vFPbbmv0kK37d30ASIp89NK1bMlA4VKXOuXlfl8AGSPzXwFUYAKcx_oia28Y-gobtbOnCx-KJnjJ_MlBlk1WM9D$>, in the introduction.md file you have a typo at line 7: "instrement". In the same file at line 48, please use the livelabs.oracle.com link instead of the apexapps.oracle.com one.
Please make sure your images files are lowercased. (ex: 1-2-OKE.png).
In the learn-more.md file please replace the apexapps.oracle.com URL with https://livelabs.oracle.com/pls/apex/r/dbpm/livelabs/view-workshop?wid=3350 on line 28 and 33.
The existing Get Started version for the freetier version should be replaced with the right version, the existing one is pointing to the sandbox environment.
Thank you!

**Review by carmenberdant1 — COMMENTED** [review]
Hi @yutakats, the images are still in uppercase and the Get Started lab for the freetier version is not the right one. Thank you!

**Comment by carmenberdant1** [comment]
@yutakats, this branch is out-of-date, please merge the latest changes from the main.

**Comment by yutakats** [comment]
> @yutakats, this branch is out-of-date, please merge the latest changes from the main.

Just saw this message. Sorry. I just merged to upstream/main. Do you see my changes now..? 

Also, would you please clarify what do you mean by  "Get Started lab for the freetier version is not the right one"?  Do you mean the link to the "Get started with APM" in the lab-8 "Learn more", is not right? I did change the URL from apex to livelabs as you mentioned.  But the Get Started lab is a green button lab, and no free tier is available..  If this is not what you meant, appreciate if you can clarify. - thank you, Yutaka

**Pull request closed without merging**
