### PR TITLE
 WMS ID 11471 HOL 2523 Build an intelligent Data Lake for your Enterprise Data Platform 

### PR DESCRIPTION
**Pull request by mariomiola**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramumg — CHANGES_REQUESTED** [review]
Hi @mariomiola, 

- your prerequisite section in the introduction is empty.
- can you please add a space between this workshop... and estimated time. 
image
- make sure you end every lab with 
image

Thank you, 
Ramu

**Comment by mariomiola** [comment]
Hi @ramumg - updates are in https://github.com/oracle-livelabs/oci/pull/239/commits/9ce147133183ffdba7f9ce05168a1af684f5ca79 - thanks for checking - Mario

**Review by anooshapilli — COMMENTED** [review]
@mariomiola - Please make these changes to the workshop
- In the individual labs, the lab title and the title in the manifest.json file should match. Update either of the titles to match
- In Labs 3, 4, and 5 make objectives heading 3 and update Task X - to Task X:
- Fix the Ack typo to "Acknowledgements" in all the labs.
- The link to Lab 6 is broken, please fix the path - https://mariomiola.github.io/oci/oci-dataflow/data-platform/workshops/ocw23-livelabs/?lab=scheduling-orchestration

**Comment by anooshapilli** [comment]
@mariomiola - Just following up on the requested changes

**Comment by mariomiola** [comment]
@anooshapilli - updates just provided - thanks for checking.

**Comment by denisemyrick** [comment]
Hi @mariomiola unless I missed it it looks like you added the objectives to the introduction but not each individual lab. See Section 4 of the QA checklist.

**Comment by mariomiola** [comment]
> Hi @mariomiola unless I missed it it looks like you added the objectives to the introduction but not each individual lab. See Section 4 of the QA checklist.

Objectives sections are in each of the Labs - for instance:
Screen Shot 2023-08-15 at 9 34 46 AM

**Comment by denisemyrick** [comment]
@mariomiola Sorry! Misspoke - I meant it looks like you're missing prerequisites for each lab

**Comment by mariomiola** [comment]
Hi @denisemyrick – pre-requisites sections are updated – thanks for checking

From: denisemyrick ***@***.***>
Date: Tuesday, August 15, 2023 at 10:26 AM
To: oracle-livelabs/oci ***@***.***>
Cc: Mario Miola ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] WMS ID 11471 HOL 2523 Build an intelligent Data Lake for your Enterprise Data Platform (PR #239)

@mariomiola<https://urldefense.com/v3/__https:/github.com/mariomiola__;!!ACWV5N9M2RV99hQ!Np72JzSvRx5QMkSIWK0yxrm0QT-02pVzpMvjZrYlb-FtzwF5T0oz15tSNZ7Q6STRjMtaz2YIfNAw_PoewMnq1yyjjw$> Sorry! Misspoke - I meant it looks like you're missing prerequisites for each lab

**Comment by rahul-tasker** [comment]
This branch is out of date with the base branch. Please merge the lastest changes from main into this branch so it can be approved. Thanks!

**Comment by anooshapilli** [comment]
@mariomiola - Please make these changes to approve the PR
- Remove the word lab at the end of each lab title in the markdown file. 
- In Lab 4 Update the numbering of Task 4 to Task 3
- In Lab 5 make objectives bullets
- In Lab 6 unbold Estimated Time

**Comment by anooshapilli** [comment]
@mariomiola - This PR has been open for more than a week. Please make these changes to the workshop asap. We will be closing the PR by EOD tomorrow. Fyi, in prep for OCW, GitHub Freeze starts Aug 21st.

**Comment by mariomiola** [comment]
> @mariomiola - This PR has been open for more than a week. Please make these changes to the workshop asap. We will be closing the PR by EOD tomorrow. Fyi, in prep for OCW, GitHub Freeze starts Aug 21st.

@anooshapilli - changes requested just applied

**Pull request merged**
