### PR TITLE
Updated formatting

### PR DESCRIPTION
**Pull request by dipeshrath**
# Add here your WMS ID 11407

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by KillianLynch — DISMISSED** [review]
Hi @dipeshrath, to make the lab a little easier for the users to participate, please consider adding the copy functionality to your code block. The syntax would look like this:

    ```
    <copy>
    this is the code you want the lab users to copy and paste.
    </copy>
    ```

**Comment by dipeshrath** [comment]
> 

@KillianLynch I have used copy tag for script where applicable. I can not use copy for each code block because it is used due to rendering issues in jekyll for underscore. It does not work even add as 'string'. Most of file path are used a underscore in lab so using code block for that.

**Comment by KillianLynch** [comment]
@dipeshrath, thanks for the update; everything looks good! The only thing left is to resolve conflicts with the files `cd3-automation-toolkit/deploy-compute/deploy-compute.md` and `cd3-automation-toolkit/setup-the-toolkit/setup-the-toolkit.md` before I can merge your changes.

**Comment by dipeshrath** [comment]
@KillianLynch Resolved all conflicts.

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
