### PR TITLE
WMS ID #11411 - Next-generation Fusion Application administrative experience on Oracle Cloud Console

### PR DESCRIPTION
**Pull request by tinayak**
# WMS ID: 11411

Github page: https://tinayak.github.io/oci/faaas/workshops/OCW23-tenancy/

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ZRTalke — CHANGES_REQUESTED** [review]
Hi @tinayak 

Please re-review your workshop going through the self QA document while you do and make all appropriate updates necessary to conform to guidelines

Some of the issues I'm noticing:
- Labs need a prerequisites section
- Your Learn More section in your introduction file needs to be moved above acknowledgements and populated if you are going to use it. This section should also be present in all labs
- Images need to be indented under numbering
- Your help link in your manifest file should be your workshop stakeholder email in the WMS, not yours
- Your Get Started lab should be a link in your manifest file to the proper file mentioned in the self QA document, not self created

**Comment by tinayak** [comment]
Hi @ZRTalke , Made the changes mentioned in your comment. I have doubts regarding the below points:

- Your help link in your manifest file should be your workshop stakeholder email in the WMS, not yours
  _The help link mentioned in manifest is of the workshop owner: ankit.l.kumar@oracle.com. Is there any issue with this? If 
  yes, then what should be the correct help link?_
- Your Get Started lab should be a link in your manifest file to the proper file mentioned in the self QA document, not self created
  _We need this custom Get Started lab as we have a different way of logging into the cloud console._

**Comment by tinayak** [comment]
@ZRTalke I see the following lint-checker error: "The second H2 tag (##) of your Markdown file should be labeled with "Task". (show)". I am not sure how to avoid this in the introduction.md file as it has no tasks.

**Review by ramumg — APPROVED** [review]

**Review by ramumg — CHANGES_REQUESTED** [review]
Hi @tinayak, 
The stakeholder is livelabs-help-oci_us@oracle.com. It looks like that should be the email in your manifest for help. Also, images don't have to be separated by the task in the images folder. They would generally be under the images folder without any separation. 

Thank you, 
Ramu

**Comment by anooshapilli** [comment]
@tinayak - Please review the workshop using the Self QA Checklist in WMS, make necessary changes to the workshop and update the status to Self QA Complete in WMS.

**Review by ramumg — DISMISSED** [review]
Hi @tinayak, 

Please make sure you are using this format for your workshop folder: 
image

Thank you, 
Ramu

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
