### PR TITLE
Initial commit based on similar livelab

### PR DESCRIPTION
**Pull request by MarkHeff**
WMS ID: 11401

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by anooshapilli** [comment]
@MarkHeff - I see this workshop is In Development status in WMS. Please perform thorogh self-QA of the workshop using the Self QA Checklist in WMS and update the status to Self QA Complete to be able to review this PR.

**Comment by ramumg** [comment]
Hi @MarkHeff, 

Please let us know if you have any questions to about performing the QA. After you apply the changes needed, we will go ahead and approve your PR. 

Thank you, 
Ramu

**Comment by anooshapilli** [comment]
@MarkHeff - Following up on this PR for an update. Thank you!

**Comment by MarkHeff** [comment]
@anooshapilli @rahul-tasker I've finished the self QA and opened a new PR: https://github.com/oracle-livelabs/oci/pull/191

**Pull request closed without merging**
