### PR TITLE
WMS 11407: Review of new workshop for CD3 Automation Toolkit

### PR DESCRIPTION
**Pull request by dipeshrath**
# Add here your WMS ID 11407

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@dipeshrath - Please review the Self QA Checklist in WMS thoroughly and make necessary changes to the workshop. After updating the workshop status to Self QA Complete, we will review this PR.

**Comment by dipeshrath** [comment]
Updated status to Self QA Complete.

**Comment by hope-fisher** [comment]
Hi @dipeshrath, 

All filenames must be in all lower case, including images. Please check your filenames, as well as their reference with any corresponding files. Keep in mind that GitHub sometimes does not save files that only change name capitalization. You may need to add a unique identifier, such as 

Event_Rule.jpg --> event_rule01

or similar. Hope this helps!

**Comment by dipeshrath** [comment]
> Hi @dipeshrath,
> 
> All filenames must be in all lower case, including images. Please check your filenames, as well as their reference with any corresponding files. Keep in mind that GitHub sometimes does not save files that only change name capitalization. You may need to add a unique identifier, such as
> 
> Event_Rule.jpg --> event_rule01
> 
> or similar. Hope this helps!

Updated file names and references.

**Review by hope-fisher — APPROVED** [review]

**Pull request merged**
