### PR TITLE
OCW WMID - 11231, 11240, 11241, 11242, 11243, 11244, 11245, 11246, 11247

### PR DESCRIPTION
**Pull request by tayzheng**
# Add here your WMS ID
11231, 11240, 11241, 11242, 11243, 11244, 11245, 11246, 11247

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by malcherm** [comment]
Due to Oracle Cloud World Support and companywide freezes:
Please note that LiveLabs does not accept any PRs from October 10 until October 21.
Please see postings in the slack channels.
Your PR will be set on hold until October 21.

If this is an emergency request for OCW - please send an email to livelabs-help-db_us and make the merge conflicts are resolved.

**Comment by klazarz** [comment]
@tayzheng please accept the changes from main!

**Comment by tayzheng** [comment]
Hi,

Can you please show me some guidance on the necessary steps I need to take to accept the changes from main?

Thanks in advance!

Best,
Taylor


Taylor Zheng

Oracle North America Cloud Engineering

Phone: (737) 867-3774 | Mobile: (737) 222-1644

________________________________
From: Kevin Lazarz ***@***.***>
Sent: Friday, October 14, 2022 6:24 AM
To: oracle-livelabs/oci ***@***.***>
Cc: Taylor Zheng ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] OCW WMID - 11231, 11240, 11241, 11242, 11243, 11244, 11245, 11246, 11247 (PR #95)


@tayzheng<https://urldefense.com/v3/__https://github.com/tayzheng__;!!ACWV5N9M2RV99hQ!Iq1XBT4b42EqEQjZ_sMXHRugNI5FlJpgfXvLOcYdrOTlYM_7fiG4ond4mUAH_JLB0hHOhlqLPoV2ELtGJrGLx0eiaIw$> please accept the changes from main!

**Comment by malcherm** [comment]
These changes appear to already be merged.

**Comment by tayzheng** [comment]
Hi,

I've accepted changes from main and pushed to origin. Can you please see if the changes are up-to-date? Do I need to create another pull request?

Best,
Taylor


Taylor Zheng

Oracle North America Cloud Engineering

Phone: (737) 867-3774 | Mobile: (737) 222-1644

________________________________
From: Michelle Malcher ***@***.***>
Sent: Friday, October 14, 2022 9:21 AM
To: oracle-livelabs/oci ***@***.***>
Cc: Taylor Zheng ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] OCW WMID - 11231, 11240, 11241, 11242, 11243, 11244, 11245, 11246, 11247 (PR #95)


These changes appear to already be merged.

**Comment by tayzheng** [comment]
https://github.com/oracle-livelabs/oci/pull/96


Taylor Zheng

Oracle North America Cloud Engineering

Phone: (737) 867-3774 | Mobile: (737) 222-1644

________________________________

**Pull request closed without merging**
