### PR TITLE
WMSID 11449 AI for Travel  & AI for Healthcare - WMS ID #11410

### PR DESCRIPTION
**Pull request by madhusudhanrao-ppm**
# 11449

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by anooshapilli** [comment]
@madhusudhanrao-ppm - This workshop is in Approved status. Please update the workshop status to Self QA Complete to review this PR.

**Comment by madhusudhanrao-ppm** [comment]
@anooshapilli I have updated the WMS status to self QA completed, thanks.

**Review by KillianLynch — DISMISSED** [review]
Hi @madhusudhanrao-ppm, please 
- Remove the coloring from the Estimated Workshop time in the introduction. 
- Remove the "Build with Blocks" in the Acknowledgements in Lab 2

**Comment by madhusudhanrao-ppm** [comment]
@KillianLynch , 

* Removed coloring in introduction lab Estimated Time
* Removed Building with Blocks

**Review by ZRTalke — DISMISSED** [review]
Hi @madhusudhanrao-ppm 

It looks like your pull request includes changes for two workshops. Please include the second WMS ID

**Comment by jamessmith73** [comment]
Hi @ZRTalke I have 2 workshops in PR
1. AI for Healthcare - WMS ID #11410
2. Generative AI for Travel - WMSID 11449

**Comment by madhusudhanrao-ppm** [comment]
Hi @ZRTalke I have 2 workshops in PR

AI for Healthcare - WMS ID #11410
Generative AI for Travel - WMSID 11449

**Comment by ZRTalke** [comment]
Hi @madhusudhanrao-ppm 

I'm finishing up reviewing your pull request and the last thing I've noticed  is in your AI for Healthcare workshop there is no Lab 22 and after 21 it skips straight to 23. Please fix this numbering and I can approve your pull request

**Comment by madhusudhanrao-ppm** [comment]
@ZRTalke updated the number for AI for Healthcare - AI for Healthcare - WMS ID #11410

**Review by klazarz — APPROVED** [review]

**Pull request merged**
