### PR TITLE
Updated 1 image and small text for new feature.

### PR DESCRIPTION
**Pull request by yiby4n**
# Add here your WMS ID 11184

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramonamagadan18 — CHANGES_REQUESTED** [review]
Hi @yiby4n ! Please hide the compartment name from your image.

**Comment by klazarz** [comment]
@yiby4n More important is to blur the tenancy name

**Comment by yiby4n** [comment]
This is a LiveLabs, where the customers are in my tenancy/compartment. I purposely highlight the compartment name for them so they are in the correct location.


Thank you,
Aaron

[Oracle]
Aaron Rimel
Phone: +1 8168660651<tel:+18168660651>
Principal Product Manager
Observability and Management<https://oracle.com/manageability>


From: Kevin Lazarz ***@***.***>
Date: Wednesday, September 18, 2024 at 3:50 AM
To: oracle-livelabs/oci ***@***.***>
Cc: Aaron Rimel ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] Updated 1 image and small text for new feature. (PR #419)

@yiby4n<https://urldefense.com/v3/__https:/github.com/yiby4n__;!!ACWV5N9M2RV99hQ!Pnv-srseIy3GcRu5LRetnq9b4sKEg2_La7uF65IqoJphpFMZC1gR_-piVO5EaXHA3MX_hnjMITk5wddCb-3YvIt5UQ$> More important is to blur the tenancy name

**Comment by ramonamagadan18** [comment]
Hi @yiby4n! In that case please hide the tenancy, where the root name is visible. Thank you!

**Comment by yiby4n** [comment]
Adding additional changes

**Pull request closed without merging**
