### PR TITLE
Added a bonus lab and completed self QA

### PR DESCRIPTION
**Pull request by saipriyabalu**
# 11222

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by saipriyabalu** [comment]
Updated the labs after peer review. Also added a bonus lab.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Please solve the merge conflicts. Thanks!

**Comment by saipriyabalu** [comment]
Hi Team, 

Thanks for thoroughly reviewing my lab. I have completed the following changes as suggested by Madhu: 

- Used Grammarly and verified its correctness. Kindly ignore the grammar/spellings in the code
- Deleted the hardcoded password
- Updated the Manifest JSON based on the requested changes. 

Please let me know if there is anything.

Best regards,
Saipriya

**Review by arabellayao — APPROVED** [review]

**Review by arabellayao — CHANGES_REQUESTED** [review]
Please resolve merge conflicts on your branch. You can refer to this guide’s Troubleshooting #3 for help: https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest#Appendix:TroubleshootingTips

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
build-digital-assistant/ocw-2022-oci20-session74/lab1-introduction-to-oracle-digital-assistant/introduction.md
build-digital-assistant/ocw-2022-oci20-session74/lab2-configure-database/configure-database.md
build-digital-assistant/ocw-2022-oci20-session74/lab3-design-the-skill/design-the-skill.md
build-digital-assistant/ocw-2022-oci20-session74/lab4-personalize-the-skill/files/dialogflow_lab4.txt
build-digital-assistant/ocw-2022-oci20-session74/lab4-personalize-the-skill/files/dialogflow_step2.txt
build-digital-assistant/ocw-2022-oci20-session74/lab4-personalize-the-skill/files/dialogflow_step3.txt
build-digital-assistant/ocw-2022-oci20-session74/lab4-personalize-the-skill/personalize-the-skill.md
build-digital-assistant/ocw-2022-oci20-session74/lab5-expose-the-skill/expose-the-skill.md
build-digital-assistant/ocw-2022-oci20-session74/lab6-prepare-skill-to-send-sms/images/recovery-code.png
build-digital-assistant/ocw-2022-oci20-session74/lab6-prepare-skill-to-send-sms/prepare-skill-to-send-sms.md
build-digital-assistant/workshops/ocw2022/manifest.json

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi Markdown files should not have "<<<HEAD" or ">>>upstream/main". Please double check the content and resolve merge conflicts correctly. Thanks!

**Comment by arabellayao** [comment]
Hi! I am closing your PR. Please open a new PR and fix the suggested change. Thanks!

**Pull request closed without merging**
