### PR TITLE
WMS ID: 11285 (Workshop Creation)

### PR DESCRIPTION
**Pull request by brenorc**
WMS ID: 11285

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Make sure all images’ filenames are lower case
2. Images’ names should be descriptive instead of autogenerated names
3. All images should have descriptive alternative texts in the Markdown files for accessibility
4. Use this index.html (copy the content) for all your index.html: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/index.html 
Thanks!

**Comment by madhusudhanrao-ppm** [comment]
please provide meaningful image names for example create-compute.png also there are images with mixed cases, all image names should be lowercase 

image

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Make sure all images’ filenames are lower case
2. In  ft-prepare-dataset.md, please make sure all images have descriptive alternative texts.
Thanks!

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please make sure all images’ filenames are lower case. Thanks!

**Comment by arabellayao** [comment]
Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.

**Comment by arabellayao** [comment]
Hi team! I am closing this PR now. Please make sure all images’ filenames are lower case and then create a new PR. Thank you!

**Pull request closed without merging**
