### PR TITLE
WMSID 11410, Healthcare Innovations with Machine Learning and Artificial Intelligence 

### PR DESCRIPTION
**Pull request by madhusudhanrao-ppm**
# WMSID 11410, Healthcare Innovations with Machine Learning and Artificial Intelligence 

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@madhusudhanrao-ppm - Please make these changes to the workshop and the PR
- Email us the sql files. We will upload to object storage and share you the PAR link. You can update the workshop instructions with the PAR link to download the files.
- Remove Lab X: from the titles in the markdown files for each lab.
- Number the instructions in the Tasks

**Comment by madhusudhanrao-ppm** [comment]
I have removed .SQL files, removed Lab X: from Title and Added Task numbers for every task In all Labs

**Comment by anooshapilli** [comment]
@madhusudhanrao-ppm - Please make these changes to the workshop.
- Could you remove these lines in the Introduction Lab
image
- Make the table of contents heading 2 and number workshop X: and remove those lines in intro lab
- Make About Breast and Lung Cancer heading 2 in intro lab
- Move Prerequisites before the table the contents in intro lab
- Number the instructions in Lab 3, 5, 9, 10, 12, 13, 14, 15, 16, 17, 18
- Indent the images in Lab 8 Task 6, Lab 10 Task 6, 7, 8, Lab 13 Task 6, 7
- Lab 9 Task 4, fix the broken image - teller.png

**Comment by madhusudhanrao-ppm** [comment]
Thanks @anooshapilli  I have Numbered Labs, Changed few topics in Intro to H2, Fixed Broken Image (jpg was used instead of png), Removed line breaks, and fixed images vertical alignments

**Comment by anooshapilli** [comment]
@madhusudhanrao-ppm - Thanks for making the changes. Please number the instructions in Lab 18.

**Comment by madhusudhanrao-ppm** [comment]
Added numbering to Lab 18, Thanks.

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
