### PR TITLE
VMS 11462

### PR DESCRIPTION
**Pull request by eliana-romero**
VMS 11462

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by kamryn-v — COMMENTED** [review]
Hi @eliana-romero , 

Can you please:
 - change the InstanceOAC.png image to all lowercase letters
- Change the Addd print from reset password.txt to all lowercase letters and include dashes. It should look like add-print-from-reset-password.txt

Thanks!

**Comment by eliana-romero** [comment]
> Hi @eliana-romero ,
> 
> Can you please:
> 
> * change the InstanceOAC.png image to all lowercase letters
> * Change the Addd print from reset password.txt to all lowercase letters and include dashes. It should look like add-print-from-reset-password.txt
> 
> Thanks!

Where did you saw InstanceOAC.png and Addd print from reset password.txt?

**Comment by kamryn-v** [comment]
InstanceOAC.png is in the ft-create-autonomous-database-es-pre/images folder

Addd print from reset password.txt is in the get-started-pt/images folder

**Comment by eliana-romero** [comment]
@kamryn-v thank you, the changes are made.

**Review by kamryn-v — APPROVED** [review]

**Pull request merged**
