### PR TITLE
WMS ID #11121

### PR DESCRIPTION
**Pull request by secassessment**
# WMS ID: 11121

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ x] All filenames are lower case (including folders, images, files, etc.)
- [ x] Filenames are descriptive
- [ x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ZRTalke — CHANGES_REQUESTED** [review]
Hi @secassessment 

In the ocw-first-experience-end folder please move the two images to the images subfolder and give them descriptive names

Additionally on the WMS page please replace the development url with the github pages github.io address which uses the up to date md files in this pull request and also update the production url with the full workshop url

Thanks!

**Comment by anooshapilli** [comment]
@secassessment - Please resolve the conflicting files

**Comment by secassessment** [comment]
Hi,

I am trying to solve the conflicts but I cannot. I would need some help here please.

Regards,
Sonia

**Comment by anooshapilli** [comment]
@secassessment - Please follow the steps in Lab 3 Troubleshooting section Issue 3 to resolve the conflicting files issue - https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=3-labs-sync-github#Troubleshooting

**Pull request closed without merging**
