### PR TITLE
WMS ID: 11416 - oke-virtual-nodes initial version for ocw2023

### PR DESCRIPTION
**Pull request by junior**
# WMS ID: 11416

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@junior - This workshop is in Approved status in WMS. Please follow the steps in the guide [HERE](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=5-labs-qa-checks#Task3:SelfQA) to perform the QA of the workshop. After the workshop is updated to Self QA complete status, we will review the PR.

**Comment by anooshapilli** [comment]
@junior - Just checking for an update on this PR.

**Comment by anooshapilli** [comment]
@junior - This is a friendly reminder that the pull request (PR) has been open for over a week. Please make the requested changes and update the PR by the end of today, as we'll be closing it tomorrow. Thank you for your understanding and cooperation.

**Comment by junior** [comment]
> @junior - This is a friendly reminder that the pull request (PR) has been open for over a week. Please make the requested changes and update the PR by the end of today, as we'll be closing it tomorrow. Thank you for your understanding and cooperation.

@anooshapilli, Self-QA complete

**Review by anooshapilli — COMMENTED** [review]
@junior - Please make these changes to approve the PR
- Remove Lab from Estimated Lab Time in labs 1,2,3
- Indent the instructions and screenshots with 4 spaces from the beginning of the line for Lab 3 Task 1 and Lab 4 Task 3

**Comment by junior** [comment]
> @junior - Please make these changes to approve the PR
> 
> * Remove Lab from Estimated Lab Time in labs 1,2,3
> * Indent the instructions and screenshots with 4 spaces from the beginning of the line for Lab 3 Task 1 and Lab 4 Task 3

Done

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
