### PR TITLE
Siebel Cloud Manager new version changes committed

### PR DESCRIPTION
**Pull request by shyam-oracle**
Hi LiveLabs team,

The new version of the Siebel Cloud Manager image (CM_22.7.0) has been released and has a few modifications to the way the Siebel CRM is deployed pertaining to the Payload parameters, API endpoints, etc. I have made those changes and pushed them to the main. Kindly approve this pull request so that we have the latest content.

Regards,
Shyam Mohandas

### CODE REVIEW

**Comment by Brianna-Ambler** [comment]
Hi Shyam! Could you provide your WMS ID#? You can find that in [WMS](http://bit.ly/oraclewms).

**Review by Brianna-Ambler — CHANGES_REQUESTED** [review]
Hi Shyam! Could you provide your WMS ID#? You can find that in [WMS](http://bit.ly/oraclewms). Once I have this, I can approve your changes.

**Comment by shyam-oracle** [comment]
Hi Brianna,

The WMS id is 11097.

Regards,
Shyam

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Brianna Ambler ***@***.***>
Sent: Thursday, July 21, 2022 1:58 AM
To: oracle-livelabs/oci ***@***.***>
Cc: Shyam Mohandas ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] Siebel Cloud Manager new version changes committed (PR #6)


Hi Shyam! Could you provide your WMS ID#? You can find that in WMS<https://urldefense.com/v3/__http://bit.ly/oraclewms__;!!ACWV5N9M2RV99hQ!L7SvwGPzXNrRJOL9wkQXD7yeldEcoK_wp-KstV0FM33G1r1SwoAIC6HpYnShsJhas34NEJgp0F4POO4V4VAsuFVzLhF_$>.

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
