### PR TITLE
Made changes after QA

### PR DESCRIPTION
**Pull request by saipriyabalu**
# Add here your WMS ID - 11222

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by anooshapilli** [comment]
@saipriyabalu It is recommended to access files from object storage. Could you upload the text file to the object store, create PAR, update the PAR link in the lab and delete the text file from GitHub repo? Thanks!

**Comment by saipriyabalu** [comment]
I have raised a request to upload the file to object storage. I am waiting to get a response.

**Comment by madhusudhanrao-ppm** [comment]
@saipriyabalu PAR link has been mailed to you

**Comment by malcherm** [comment]
Since the text file is now a PAR can you please remove it from the repo. Thanks!

**Comment by saipriyabalu** [comment]
Removed all the text files from the repo. Also requested a new PAR link for one of the file

**Review by malcherm — APPROVED** [review]

**Pull request merged**
