### PR TITLE
Ocw

### PR DESCRIPTION
**Pull request by saipriyabalu**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
Please provide WMS ID, Do not include Zip Files in pull requests, this should be stored in Object storage, All filenames should be lowercase 

image

**Comment by arabellayao** [comment]
Please also update your branch with the main branch. Thanks!

**Comment by madhusudhanrao-ppm** [comment]
This branch is out-of-date with the base branch
Merge the latest changes from main into this branch.

**Comment by arabellayao** [comment]
Followed up 9/9

**Comment by arabellayao** [comment]
Hi! Please fix the changes requested, and merge from the main branch. I am closing this PR now. When you are ready, you can create a new PR. Thank!

**Pull request closed without merging**
