### PR TITLE
WMS ID: #11121

### PR DESCRIPTION
**Pull request by secassessment**
# WMS ID 11121

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x ] All filenames are lower case (including folders, images, files, etc.)
- [x ] Filenames are descriptive
- [x ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by ZRTalke** [comment]
Hi @secassessment 

It looks like your pull request is creating copies of all the workshop files. Could you please update your request to fix this issue or provide additional details.

**Comment by secassessment** [comment]
> Hi @secassessment
> 
> It looks like your pull request is creating copies of all the workshop files. Could you please update your request to fix this issue or provide additional details.

Hi, I just created the pull request as indicated in the docs. I changed all images in the workshop as the OCI console changed. Could that be the reason?

**Comment by anooshapilli** [comment]
@secassessment Moving this conversation to slack.

**Comment by ramumg** [comment]
Hi @secassessment, 

Please let me know if you need further assistance to get this PR approved. 

Thank you,
Ramu

**Comment by secassessment** [comment]
> Hi @secassessment,
> 
> Please let me know if you need further assistance to get this PR approved.
> 
> Thank you, Ramu

Hi Ramu,

Thanks a lot it would be great if you could help. What should I do to resolve the conflicts?

Regards,
Sonia

**Comment by rahul-tasker** [comment]
Hi @secassessment,

To resolve merge conflicts, please merge the latest changes from the main branch to this branch and resolve the conflicts. This [troubleshooting guide](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=3-labs-sync-github#Troubleshooting) has more details.

Thanks, 
Rahul

**Comment by anooshapilli** [comment]
@secassessment - Please join the LiveLabs Office Hours meeting tomorrow to look at resolving these conflicting files. As the PR is more than 2 weeks old closing the PR for now. Once the conflicting files are resolved, can create another PR.

**Pull request closed without merging**
