### PR TITLE
WMS ID: 11113 - OCI Developer Fast Track - Workshop Creation

### PR DESCRIPTION
**Pull request by DebySilva**
# Add here your WMS ID: 11113

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@DebySilva - Please make these changes to the workshop

- Give the images filenames descriptive titles, and make the names and extensions lowercase in the ft-resource-provision images folder and the IMG00_1.png in the ft-kub-cloud-native folder
image

image

- Give an extension to this file by adding .md to the filename
image

**Comment by anooshapilli** [comment]
@DebySilva - Following up on this PR.

**Comment by william-masdon-oracle** [comment]
@DebySilva Please review the comments on this PR. It will be closed later this week if no action is taken.

**Comment by anooshapilli** [comment]
@DebySilva - As there was no update on this PR, closing the PR. Please create a new PR after making the above changes.

**Pull request closed without merging**
